package com.example.elementpuzzledrag

data class StageSpec(
    val backgroundResId: Int,
    val monsters: List<MonsterSpec>,
)

data class MonsterSpec(
    val attribute: DropType,
    val attackPower: Int,
    val hp: Int,
    val maxRemainingAttackTurns: Int,
    val initialRemainingAttackTurns: Int? = null,
    val hpGaugeSize: Monster.HpGaugeSize,
    val resId: Int,
    val centerXOffsetFromStageCenter: Float,
    val centerYOffsetFromStageCenter: Float,
    val drawWidth: Float? = null,
    val drawHeight: Float? = null,
    val attackMotionDistance: Float? = null,
    val attackMotionSpeed: Float? = null,
)

object StageData {
    val stages = listOf(
        StageSpec(
            backgroundResId = R.mipmap.stage1,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.FIRE,
                    attackPower = 1000,
                    hp = 500,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_firemonmus,
                    centerXOffsetFromStageCenter = 0f,
                    centerYOffsetFromStageCenter = 0f,
                ),
                MonsterSpec(
                    attribute = DropType.LEAF,
                    attackPower = 1000,
                    hp = 500,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_leafmonmus,
                    centerXOffsetFromStageCenter = -300f,
                    centerYOffsetFromStageCenter = 100f,
                ),
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 1000,
                    hp = 500,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_watermonmus,
                    centerXOffsetFromStageCenter = 300f,
                    centerYOffsetFromStageCenter = 100f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage2,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.DARK,
                    attackPower = 1000,
                    hp = 700,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_keroberos,
                    centerXOffsetFromStageCenter = -145f,
                    centerYOffsetFromStageCenter = 36f,
                ),
                MonsterSpec(
                    attribute = DropType.LEAF,
                    attackPower = 1000,
                    hp = 700,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_reptiles,
                    centerXOffsetFromStageCenter = 135f,
                    centerYOffsetFromStageCenter = 99f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage3,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.DARK,
                    attackPower = 2000,
                    hp = 1000,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_zombie,
                    centerXOffsetFromStageCenter = -250f,
                    centerYOffsetFromStageCenter = 70f,
                ),
                MonsterSpec(
                    attribute = DropType.FIRE,
                    attackPower = 2000,
                    hp = 1200,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.MEDIUM,
                    resId = R.mipmap.m_wolfman,
                    centerXOffsetFromStageCenter = 40f,
                    centerYOffsetFromStageCenter = 126f,
                ),
                MonsterSpec(
                    attribute = DropType.DARK,
                    attackPower = 2000,
                    hp = 1000,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_skeleton,
                    centerXOffsetFromStageCenter = 270f,
                    centerYOffsetFromStageCenter = 70f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage4,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.LEAF,
                    attackPower = 100000,
                    hp = 10000,
                    maxRemainingAttackTurns = 10,
                    hpGaugeSize = Monster.HpGaugeSize.LARGE,
                    resId = R.mipmap.m_totem,
                    centerXOffsetFromStageCenter = 0f,
                    centerYOffsetFromStageCenter = 10f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage5,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.LIGHT,
                    attackPower = 1500,
                    hp = 2000,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_bee,
                    centerXOffsetFromStageCenter = -300f,
                    centerYOffsetFromStageCenter = -135f,
                ),
                MonsterSpec(
                    attribute = DropType.DARK,
                    attackPower = 1500,
                    hp = 2000,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_bat,
                    centerXOffsetFromStageCenter = 0f,
                    centerYOffsetFromStageCenter = 95f,
                ),
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 2000,
                    hp = 2000,
                    maxRemainingAttackTurns = 2,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_dragonfly,
                    centerXOffsetFromStageCenter = 285f,
                    centerYOffsetFromStageCenter = -130f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage6,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.FIRE,
                    attackPower = 1500,
                    hp = 3000,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_firewolf,
                    centerXOffsetFromStageCenter = -260f,
                    centerYOffsetFromStageCenter = 110f,
                ),
                MonsterSpec(
                    attribute = DropType.FIRE,
                    attackPower = 8000,
                    hp = 10000,
                    maxRemainingAttackTurns = 4,
                    hpGaugeSize = Monster.HpGaugeSize.MEDIUM,
                    resId = R.mipmap.m_firedragon,
                    centerXOffsetFromStageCenter = 70f,
                    centerYOffsetFromStageCenter = 10f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage7,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 2000,
                    hp = 5000,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_slime,
                    centerXOffsetFromStageCenter = -305f,
                    centerYOffsetFromStageCenter = 55f,
                ),
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 5000,
                    hp = 8000,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_axolotl,
                    centerXOffsetFromStageCenter = 0f,
                    centerYOffsetFromStageCenter = 70f,
                ),
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 2000,
                    hp = 5000,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_slime,
                    centerXOffsetFromStageCenter = 300f,
                    centerYOffsetFromStageCenter = 50f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage8,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.LIGHT,
                    attackPower = 3500,
                    hp = 8000,
                    maxRemainingAttackTurns = 2,
                    initialRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_angel1,
                    centerXOffsetFromStageCenter = -205f,
                    centerYOffsetFromStageCenter = 20f,
                ),
                MonsterSpec(
                    attribute = DropType.LIGHT,
                    attackPower = 3500,
                    hp = 8000,
                    maxRemainingAttackTurns = 2,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_angel2,
                    centerXOffsetFromStageCenter = 175f,
                    centerYOffsetFromStageCenter = 5f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage9,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.DARK,
                    attackPower = 3000,
                    hp = 5000,
                    maxRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_harpy,
                    centerXOffsetFromStageCenter = -260f,
                    centerYOffsetFromStageCenter = 115f,
                ),
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 5000,
                    hp = 10000,
                    maxRemainingAttackTurns = 3,
                    initialRemainingAttackTurns = 4,
                    hpGaugeSize = Monster.HpGaugeSize.MEDIUM,
                    resId = R.mipmap.m_leviathan,
                    centerXOffsetFromStageCenter = -10f,
                    centerYOffsetFromStageCenter = -35f,
                ),
                MonsterSpec(
                    attribute = DropType.LIGHT,
                    attackPower = 4000,
                    hp = 5000,
                    maxRemainingAttackTurns = 2,
                    hpGaugeSize = Monster.HpGaugeSize.SMALL,
                    resId = R.mipmap.m_windmonmus,
                    centerXOffsetFromStageCenter = 275f,
                    centerYOffsetFromStageCenter = 110f,
                ),
            ),
        ),
        StageSpec(
            backgroundResId = R.mipmap.stage10,
            monsters = listOf(
                MonsterSpec(
                    attribute = DropType.LEAF,
                    attackPower = 5000,
                    hp = 15000,
                    maxRemainingAttackTurns = 3,
                    initialRemainingAttackTurns = 1,
                    hpGaugeSize = Monster.HpGaugeSize.MEDIUM,
                    resId = R.mipmap.m_leafwitch,
                    centerXOffsetFromStageCenter = -190f,
                    centerYOffsetFromStageCenter = 95f,
                ),
                MonsterSpec(
                    attribute = DropType.WATER,
                    attackPower = 5000,
                    hp = 15000,
                    maxRemainingAttackTurns = 3,
                    initialRemainingAttackTurns = 2,
                    hpGaugeSize = Monster.HpGaugeSize.MEDIUM,
                    resId = R.mipmap.m_waterwitch,
                    centerXOffsetFromStageCenter = 80f,
                    centerYOffsetFromStageCenter = -135f,
                ),
                MonsterSpec(
                    attribute = DropType.FIRE,
                    attackPower = 5000,
                    hp = 15000,
                    maxRemainingAttackTurns = 3,
                    hpGaugeSize = Monster.HpGaugeSize.MEDIUM,
                    resId = R.mipmap.m_firewitch,
                    centerXOffsetFromStageCenter = 225f,
                    centerYOffsetFromStageCenter = 150f,
                ),
            ),
        ),
    )
}